name: Monthly Demo

on:
  schedule:
    # Run on the 1st, 2nd, and 3rd day of each month at 9 AM UTC
    - cron: '0 9 1-3 * *'
  workflow_dispatch:
    inputs:
      force_failure:
        description: 'Force test failure for demo'
        type: boolean
        default: false

jobs:
  flaky-demo-test:
    runs-on: ubuntu-latest
    permissions:
      contents: write      # For creating fix PRs
      issues: write        # For creating issues
      pull-requests: write # For creating PRs
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
    
    - name: Run flaky demo test
      id: demo-test
      run: |
        cd demo
        npm install
        # Run Jest tests and capture both stdout and stderr
        mkdir -p test-results
        npm test 2>&1 | tee test-results/jest-output.log || true
        # Jest will automatically generate junit.xml in test-results/
        # Copy any additional Jest output files
        if [ -f coverage/lcov-report/index.html ]; then
          cp coverage/lcov-report/index.html test-results/coverage.html
        fi
        echo "Demo test completed - analyzing real Jest output"
        exit 1
    
    - name: Force failure for demo (if requested)
      if: inputs.force_failure == true
      run: |
        echo "Simulating test failure for demonstration"
        exit 1
    
    - name: Claude Code Watchdog Analysis
      if: failure()
      id: watchdog
      continue-on-error: true  # Don't let watchdog errors break the demo summary
      uses: ./  # Use the local action
      with:
        anthropic_api_key: ${{ secrets.ANTHROPIC_API_KEY }}
        test_results_path: 'demo/test-results/*'
        create_fixes: 'true'
        rerun_tests: 'false'  # Don't rerun for demo
        severity_threshold: 'low'
        debug_mode: 'true'
        safe_mode: 'true'  # Enable safe mode for demo
    
    - name: Demo results summary
      if: always()
      run: |
        echo "🎭 Demo Run Complete!"
        echo "Test Status: ${{ steps.demo-test.outcome }}"
        
        if [ "${{ steps.demo-test.outcome }}" = "failure" ]; then
          echo "Watchdog Analysis:"
          echo "  - Severity: ${{ steps.watchdog.outputs.severity }}"
          echo "  - Action taken: ${{ steps.watchdog.outputs.action_taken }}"
          echo "  - Issue number: ${{ steps.watchdog.outputs.issue_number }}"
          echo "  - PR number: ${{ steps.watchdog.outputs.pr_number }}"
          echo "  - Tests passing: ${{ steps.watchdog.outputs.tests_passing }}"
        else
          echo "✅ Tests passed - no watchdog analysis needed"
        fi
        
        echo ""
        echo "🔍 Check the Actions tab for:"
        echo "  - Analysis report artifacts"
        echo "  - Debug data (if failure occurred)"
        echo "  - Any issues or PRs created by Artemis"