name: Monthly Demo

on:
  schedule:
    # Run on the 1st, 2nd, and 3rd day of each month at 9 AM UTC
    - cron: '0 9 1-3 * *'
  workflow_dispatch:
    inputs:
      force_failure:
        description: 'Force test failure for demo'
        type: boolean
        default: false

jobs:
  flaky-demo-test:
    runs-on: ubuntu-latest
    permissions:
      contents: write      # For creating fix PRs
      issues: write        # For creating issues
      pull-requests: write # For creating PRs
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
    
    - name: Run flaky demo test
      id: demo-test
      run: |
        cd demo
        npm install
        # Create test results directory
        mkdir -p test-results
        # Run tests and capture output
        npm test 2>&1 | tee test-results/npm-test-output.log || true
        # Also create a fake JUnit XML for testing
        cat > test-results/junit.xml << 'EOF'
<?xml version="1.0" encoding="UTF-8"?>
<testsuites name="Demo Tests" tests="3" failures="1" errors="0" time="2.5">
  <testsuite name="Math Operations" tests="2" failures="0" errors="0" time="1.2">
    <testcase name="should add numbers correctly" time="0.5"/>
    <testcase name="should multiply numbers correctly" time="0.7"/>
  </testsuite>
  <testsuite name="String Operations" tests="1" failures="1" errors="0" time="1.3">
    <testcase name="should concatenate strings" time="1.3">
      <failure message="AssertionError: expected 'helloworld' to equal 'hello world'">
        Expected: "hello world"
        Received: "helloworld"
      </failure>
    </testcase>
  </testsuite>
</testsuites>
EOF
        # Exit with failure to trigger watchdog
        exit 1
    
    - name: Force failure for demo (if requested)
      if: inputs.force_failure == true
      run: |
        echo "Simulating test failure for demonstration"
        exit 1
    
    - name: Claude Code Watchdog Analysis
      if: failure()
      id: watchdog
      continue-on-error: true  # Don't let watchdog errors break the demo summary
      uses: ./  # Use the local action
      with:
        anthropic_api_key: ${{ secrets.ANTHROPIC_API_KEY }}
        test_results_path: 'demo/test-results/*'
        create_fixes: 'true'
        rerun_tests: 'false'  # Don't rerun for demo
        severity_threshold: 'low'
        debug_mode: 'true'
        safe_mode: 'true'  # Enable safe mode for demo
    
    - name: Demo results summary
      if: always()
      run: |
        echo "🎭 Demo Run Complete!"
        echo "Test Status: ${{ steps.demo-test.outcome }}"
        
        if [ "${{ steps.demo-test.outcome }}" = "failure" ]; then
          echo "Watchdog Analysis:"
          echo "  - Severity: ${{ steps.watchdog.outputs.severity }}"
          echo "  - Action taken: ${{ steps.watchdog.outputs.action_taken }}"
          echo "  - Issue number: ${{ steps.watchdog.outputs.issue_number }}"
          echo "  - PR number: ${{ steps.watchdog.outputs.pr_number }}"
          echo "  - Tests passing: ${{ steps.watchdog.outputs.tests_passing }}"
        else
          echo "✅ Tests passed - no watchdog analysis needed"
        fi
        
        echo ""
        echo "🔍 Check the Actions tab for:"
        echo "  - Analysis report artifacts"
        echo "  - Debug data (if failure occurred)"
        echo "  - Any issues or PRs created by Artemis"